(function(){
  const hasConfig=()=>Boolean(window.APP_CONFIG?.SUPABASE_URL && window.APP_CONFIG?.SUPABASE_ANON_KEY && window.supabase);
  if(!hasConfig()) return;
  const client=window.supabase.createClient(window.APP_CONFIG.SUPABASE_URL,window.APP_CONFIG.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  window.DarsitaOnline={client,session:null,ready:false};
  const $=s=>document.querySelector(s);let syncing=false;
  const toast=t=>{const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),2800)};
  const appReady=()=>typeof state!=='undefined';
  function setOnline(on){if(appReady()){state.online=on;if(typeof syncHeader==='function')syncHeader()}const label=$('#online-label'),sub=$('#online-sub'),status=$('#statusText');if(label)label.textContent=on?'آنلاین':'حالت آزمایشی';if(sub)sub.textContent=on?'داده‌ها در حساب شما ذخیره می‌شوند':'اتصال دیتابیس در دسترس نیست';if(status)status.textContent=on?'حساب آنلاین فعال':'نسخه محلی فعال'}
  const normalizeDigits=v=>String(v||'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d));
  function iranPhone(value){const raw=normalizeDigits(value).replace(/\s|[-()]/g,'');if(/^\+98\d{10}$/.test(raw))return raw;if(/^0098\d{10}$/.test(raw))return '+'+raw.slice(2);if(/^09\d{9}$/.test(raw))return '+98'+raw.slice(1);if(/^9\d{9}$/.test(raw))return '+98'+raw;return raw}
  const phoneLooksValid=value=>/^\+98\d{10}$/.test(iranPhone(value));
  const authFunction=()=>window.APP_CONFIG.SUPABASE_URL.replace(/\/$/,'')+'/functions/v1/telegram-auth';
  async function telegramAuth(payload){const r=await fetch(authFunction(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let data={};try{data=await r.json()}catch{}if(!r.ok||data.error)throw new Error(data.error||'ارتباط با سامانه تأیید ناموفق بود.');return data}
  async function ensureProfile(user){const meta=user.user_metadata||{},name=(meta.name||meta.full_name||user.email?.split('@')[0]||user.phone||'کاربر').trim().slice(0,80);const {data,error}=await client.from('profiles').upsert({id:user.id,name,email:user.email||null},{onConflict:'id'}).select().single();if(error)throw error;if(appReady()){state.data.users=state.data.users||[];const u={id:data.id,name:data.name,email:data.email||user.email||'',phone:user.phone||'',createdAt:data.created_at,role:data.role||'user'};const i=state.data.users.findIndex(x=>x.id===u.id);i>=0?state.data.users[i]=u:state.data.users.push(u);state.data.currentUserId=u.id;state.user=u;if(typeof save==='function')save()}return data}
  async function loadOnlineData(user){const [{data:acts,error:aErr},{data:rooms,error:rErr}]=await Promise.all([client.from('activities').select('*').order('created_at',{ascending:false}).limit(500),client.from('rooms').select('*').order('created_at',{ascending:false}).limit(100)]);if(aErr)throw aErr;if(rErr)throw rErr;if(appReady()){state.data.activities=(acts||[]).map(a=>({id:a.id,userId:a.user_id,date:a.date,subject:a.subject,type:a.type,minutes:a.minutes,tests:a.tests,correct:a.correct,wrong:a.wrong,blank:a.blank,createdAt:a.created_at,_online:true}));state.data.rooms=(rooms||[]).map(r=>({id:r.id,name:r.name,subject:r.subject,capacity:r.capacity,ownerId:r.owner_id,members:0,createdAt:r.created_at,_online:true}));state.data.currentUserId=user.id;state.user=state.data.users.find(x=>x.id===user.id)||state.user;if(typeof save==='function')save();if(typeof syncHeader==='function')syncHeader();const key=location.hash.replace('#','');if(key==='dashboard'&&typeof dashboard==='function')dashboard();else if(key&&key!=='chat'&&key!=='admin'&&typeof routePage==='function')routePage(key)}}
  async function syncLocalActivities(user){if(!appReady()||syncing)return;const list=(state.data.activities||[]).filter(a=>a.userId===user.id&&!a._online&&!a._syncing);if(!list.length)return;syncing=true;try{for(const a of list){a._syncing=true;const {data,error}=await client.from('activities').insert({user_id:user.id,date:a.date,subject:a.subject,type:a.type,minutes:Number(a.minutes||0),tests:Number(a.tests||0),correct:Number(a.correct||0),wrong:Number(a.wrong||0),blank:Number(a.blank||0)}).select().single();if(error){delete a._syncing;continue}a.id=data.id;a.userId=data.user_id;a._online=true;delete a._syncing}if(typeof save==='function')save()}finally{syncing=false}}
  function authModal(){
    const old=$('#onlineAuthModal');if(old)old.remove();
    const el=document.createElement('div');el.id='onlineAuthModal';el.className='modal';
    el.innerHTML='<div class="modal-backdrop" data-online-close></div><div class="modal-card online-auth-card"><div class="auth-tabs"><button class="auth-tab active" data-tab="login">ورود</button><button class="auth-tab" data-tab="signup">ثبت‌نام</button></div><div class="online-auth-body"><h2 id="authTitle">ورود به حساب</h2><p id="authHint">برای ورود، شماره موبایل یا ایمیل و رمز عبور را وارد کن.</p><form id="onlineAuthForm"><div class="auth-name-wrap" hidden><label>نام نمایشی<input id="onlineName" maxlength="80" placeholder="مثلاً محمد" autocomplete="name"></label></div><div id="loginIdentityField"><label>شماره موبایل یا ایمیل<input id="onlineIdentity" autocomplete="username" required></label></div><div id="emailField" hidden><label>ایمیل<input id="onlineEmail" type="email" autocomplete="email"></label></div><div id="passwordField"><label>رمز عبور<input id="onlinePassword" type="password" minlength="12" autocomplete="current-password" required></label></div><div id="phoneField" hidden><label>شماره موبایل<input id="onlinePhone" type="tel" inputmode="tel" maxlength="16" placeholder="09123456789" autocomplete="tel"></label></div><div id="telegramStep" hidden></div><button class="primary-btn" type="submit" id="onlineAuthSubmit">ورود</button></form><button class="text-btn" id="onlineReset">بازیابی رمز عبور</button><div id="onlineAuthMsg" class="auth-message"></div></div></div>';
    document.body.appendChild(el);el.classList.add('show');
    let mode='login',step='form',challengeToken='',pendingPhone='',botUrl='';
    const nameWrap=el.querySelector('.auth-name-wrap'),loginIdentityField=$('#loginIdentityField'),emailField=$('#emailField'),passwordField=$('#passwordField'),phoneField=$('#phoneField'),telegramStep=$('#telegramStep'),resetBtn=$('#onlineReset');
    const render=()=>{el.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===mode));const signup=mode==='signup';nameWrap.hidden=!signup;loginIdentityField.hidden=signup;emailField.hidden=true;passwordField.hidden=signup&&step==='form';phoneField.hidden=!signup;telegramStep.hidden=!signup||step==='form';$('#authTitle').textContent=!signup?'ورود به حساب':(step==='form'?'ساخت حساب جدید':'تأیید تلگرام');$('#authHint').textContent=!signup?'شماره موبایل یا ایمیل و رمز عبور خود را وارد کن.':(step==='form'?'نام، شماره موبایل و یک رمز عبور قوی وارد کن؛ سپس با ربات تلگرام شماره را تأیید کن.':'داخل ربات Start را بزن، شماره‌ات را با دکمهٔ ارسال شماره من بفرست و کد ۶ رقمی را اینجا وارد کن.');$('#onlineAuthSubmit').textContent=!signup?'ورود':(step==='form'?'ادامه و باز کردن تلگرام':'تأیید و ساخت حساب');resetBtn.hidden=signup;if(signup&&step==='telegram')telegramStep.innerHTML='<div class="telegram-verify-box"><a class="primary-btn" href="'+botUrl+'" target="_blank" rel="noopener">باز کردن ربات تلگرام ↗</a><label>کد ۶ رقمی<input id="onlineTelegramOtp" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="۱۲۳۴۵۶"></label><small>در ربات Start و سپس «ارسال شماره من» را بزن.</small></div>'};
    el.addEventListener('click',e=>{if(e.target.closest('[data-online-close]')){el.remove();return}const tab=e.target.closest('[data-tab]');if(tab){mode=tab.dataset.tab;step='form';challengeToken='';pendingPhone='';botUrl='';$('#onlineAuthMsg').textContent='';$('#onlineAuthForm').reset();render()}});
    $('#onlineAuthForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#onlineAuthMsg');msg.textContent='در حال پردازش...';try{
      if(mode==='login'){const identity=$('#onlineIdentity').value.trim(),password=$('#onlinePassword').value;if(!identity||!password){msg.textContent='شماره/ایمیل و رمز عبور را وارد کن.';return}const payload=identity.includes('@')?{email:identity,password}:{phone:iranPhone(identity),password};const res=await client.auth.signInWithPassword(payload);if(res.error)throw res.error;el.remove();toast('ورود موفق بود');return}
      if(step==='form'){const name=$('#onlineName').value.trim(),phone=iranPhone($('#onlinePhone').value),password=$('#onlinePassword').value;if(!name){msg.textContent='نام نمایشی را وارد کن.';return}if(!phoneLooksValid(phone)){msg.textContent='شماره موبایل معتبر ایران وارد کن.';return}if(password.length<12){msg.textContent='رمز عبور باید حداقل ۱۲ کاراکتر باشد.';return}const res=await telegramAuth({action:'create_challenge',phone,name});challengeToken=res.challengeToken;pendingPhone=phone;botUrl=res.botUrl;step='telegram';render();msg.textContent='وارد ربات شو، شماره‌ات را ارسال کن و سپس کد را اینجا وارد کن.';return}
      const otp=normalizeDigits($('#onlineTelegramOtp').value).replace(/\D/g,'');if(!/^\d{6}$/.test(otp)){msg.textContent='کد ۶ رقمی را درست وارد کن.';return}await telegramAuth({action:'verify_otp',challengeToken,otp,password:$('#onlinePassword').value});const login=await client.auth.signInWithPassword({phone:pendingPhone,password:$('#onlinePassword').value});if(login.error)throw login.error;el.remove();toast('حساب با موفقیت ساخته شد');
    }catch(err){console.error(err);msg.textContent=err?.message||'عملیات ناموفق بود.'}});
    resetBtn.addEventListener('click',async()=>{const identity=$('#onlineIdentity').value.trim();const email=identity.includes('@')?identity:'';if(!email){$('#onlineAuthMsg').textContent='برای بازیابی رمز، ایمیل را وارد کن.';return}const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('#onlineAuthMsg').textContent=error?'بازیابی ناموفق بود.':'لینک بازیابی ارسال شد.'});
    render();
  }
  document.addEventListener('click',e=>{const auth=e.target.closest('#authBtn,#profileQuick');if(!auth)return;e.preventDefault();e.stopImmediatePropagation();if(window.DarsitaOnline.session)client.auth.signOut().catch(err=>toast(err.message));else authModal()},true);
  async function boot(){try{const {data,error}=await client.auth.getSession();if(error)throw error;window.DarsitaOnline.session=data.session;window.DarsitaOnline.ready=true;if(data.session){await ensureProfile(data.session.user);await loadOnlineData(data.session.user);setOnline(true);await syncLocalActivities(data.session.user)}else setOnline(false)}catch(err){console.error(err);setOnline(false)}client.auth.onAuthStateChange(async(_event,session)=>{window.DarsitaOnline.session=session;if(session){try{const p=await ensureProfile(session.user);await loadOnlineData(session.user);await syncLocalActivities(session.user);setOnline(true);window.dispatchEvent(new CustomEvent('darsita:auth-ready',{detail:p}));if(location.hash==='#chat'&&window.refreshChat)window.refreshChat()}catch(err){console.error(err);toast('ورود انجام شد ولی دریافت داده‌ها خطا داشت')}}else{if(appReady()){state.data.currentUserId=null;state.user=null;if(typeof save==='function')save()}setOnline(false);if(typeof dashboard==='function')dashboard();window.dispatchEvent(new CustomEvent('darsita:auth-ready',{detail:null}))}});setInterval(()=>{if(window.DarsitaOnline.session)syncLocalActivities(window.DarsitaOnline.session.user).catch(console.error)},5000)}
  window.supabaseClient=client;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
