CREATE TABLE users (
 id SERIAL PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 phone VARCHAR(20) UNIQUE NOT NULL,
 telegram_id VARCHAR(100),
 password_hash TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE otp_codes (
 id SERIAL PRIMARY KEY,
 phone VARCHAR(20) NOT NULL,
 code VARCHAR(6) NOT NULL,
 expires_at TIMESTAMP NOT NULL
);
